// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCncqsh9qQWJ4dUuy2VFx5Y5cI_q4UpQ88',
    appId: '1:290527945432:web:8baf669fb40a6e19ff6dad',
    messagingSenderId: '290527945432',
    projectId: 'trimandtask',
    authDomain: 'trimandtask.firebaseapp.com',
    storageBucket: 'trimandtask.appspot.com',
    measurementId: 'G-2807X4PCY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbcQe4SZAmNzKGLPY3Kg-4ORUakFrMa3E',
    appId: '1:290527945432:android:140cbe0545b4e599ff6dad',
    messagingSenderId: '290527945432',
    projectId: 'trimandtask',
    storageBucket: 'trimandtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xRWxFLyREmLoVyXIGkeJInAUhw0vJcg',
    appId: '1:290527945432:ios:8325298f28709272ff6dad',
    messagingSenderId: '290527945432',
    projectId: 'trimandtask',
    storageBucket: 'trimandtask.appspot.com',
    iosBundleId: 'com.example.trimVid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4xRWxFLyREmLoVyXIGkeJInAUhw0vJcg',
    appId: '1:290527945432:ios:8325298f28709272ff6dad',
    messagingSenderId: '290527945432',
    projectId: 'trimandtask',
    storageBucket: 'trimandtask.appspot.com',
    iosBundleId: 'com.example.trimVid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCncqsh9qQWJ4dUuy2VFx5Y5cI_q4UpQ88',
    appId: '1:290527945432:web:573e4135cb7c218bff6dad',
    messagingSenderId: '290527945432',
    projectId: 'trimandtask',
    authDomain: 'trimandtask.firebaseapp.com',
    storageBucket: 'trimandtask.appspot.com',
    measurementId: 'G-ZC3F7YYPQ3',
  );

}